import type { Article } from './types';

// This data has been cleaned and parsed from the provided CSV.
// - Filtered header/footer/junk lines.
// - Corrected character encoding issues.
// - Parsed numbers and stringified prices with commas.
export const initialArticles: Omit<Article, 'environnementId'>[] = [
  { id: '11', location: 'F.2.1.E', name: 'HALOGENE NORMA H1TR', stock: 9, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '27', location: 'F.2.5.D', name: 'AMPOULE PHILIPS', stock: 7, packaging: 'BLI2', price: 15, status: 'Actif' },
  { id: '23371', location: 'D.1.6.E', name: 'RECHANGE SOUFFLET', stock: 1, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '98190218', location: 'D.2.1.C', name: 'ÉCRAN AVANT FUMÉE', stock: 5, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '147174', location: 'F.3.3.I', name: 'COLLIER SERFLEX', stock: 2, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '180782', location: 'A.2.4.E', name: 'COLLIER BP 13 PLUS', stock: 1, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '185350', location: 'D.1.1.C', name: 'COLLIER DE SERRAGE', stock: 8, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '185404', location: 'A.2.4.B', name: 'COLLIER SERFLEX 14', stock: 5, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '18598', location: 'D.1.1.E', name: 'COLLIER DE SERRAGE', stock: 11, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '2070649', location: 'F.3.6.B', name: 'FEU ARRIERE', stock: 6, packaging: 'PIEC', price: 8, status: 'Actif' },
  { id: '2077003', location: 'F.2.4.C', name: 'VOYANT ROUGE', stock: 7, packaging: 'PIEC', price: 5, status: 'Actif' },
  { id: '023121P', location: 'E.1.6.C', name: 'JOINT COUVRE CULASSE', stock: 7, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '023600P', location: 'A.2.4.A', name: 'JOINT COUVRE CULASSE', stock: 6, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '411321009', location: 'F.3.3.E', name: 'RIVETS', stock: 3, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: '411400609', location: 'F.3.3.B', name: 'RIVETS', stock: 3, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '411481209', location: 'F.3.3.F', name: 'RIVETS', stock: 3, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '419401019', location: 'F.3.3.A', name: 'RIVETS', stock: 6, packaging: 'PIEC', price: 5, status: 'Actif' },
  { id: '67712', location: 'A.1.4.H', name: 'ANTI-BROUILLARD', stock: 9, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '67716', location: 'A.2.4.F', name: 'ANTI-BROUILLARD', stock: 7, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '69087', location: 'A.2.1.A', name: 'CUVELAGE', stock: 1, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '69580', location: 'D.3.1.D', name: 'ENSEMBLE DE FIXATION', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '69586', location: 'F.2.3.F', name: 'VALEO ECLAIRAGE', stock: 7, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '07EPDM', location: 'F.2.4.A', name: 'FEUX DE GABARIT', stock: 8, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '82897', location: 'F.2.4.B', name: 'VOYANT FEUX', stock: 3, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '85026', location: 'A.1.3.E', name: 'VALEO ECLAIRAGE', stock: 10, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '1.830.008', location: 'C.1.4.H', name: 'BOUCHON', stock: 7, packaging: 'PIEC', price: 18, status: 'Actif' },
  { id: '1.850.001', location: 'C.1.4.A', name: 'BOUCHON', stock: 6, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '1.850.011', location: 'C.1.5.D', name: 'BOUCHON', stock: 2, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '1.850.076', location: 'C.1.4.I', name: 'BOUCHON', stock: 1, packaging: 'PIEC', price: 16, status: 'Actif' },
  { id: '1.850.111', location: 'C.1.2.A', name: 'BOUCHON', stock: 1, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '1.850.127', location: 'C.1.5.F', name: 'BOUCHON', stock: 5, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '1000000000', location: 'C.1.2.F', name: 'MASSE EQUILIBRAGE', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '10A00825', location: 'E.1.1.B', name: 'COURROIE', stock: 4, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: '10A0540C', location: 'E.1.1.D', name: 'COURROIE', stock: 1, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '10A0595', location: 'E.1.5.C', name: 'COURROIE', stock: 8, packaging: 'PIEC', price: 13, status: 'Actif' },
  { id: '10A0605', location: 'E.1.4.E', name: 'COURROIE', stock: 11, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '10A0825', location: 'E.1.1.B', name: 'COURROIE', stock: 8, packaging: 'PIEC', price: 13, status: 'Actif' },
  { id: '10A0840', location: 'E.1.4.D', name: 'COURROIE', stock: 3, packaging: 'PIEC', price: 9, status: 'Actif' },
  { id: '10A0850', location: 'E.1.5.A', name: 'COURROIE', stock: 2, packaging: 'PIEC', price: 7, status: 'Actif' },
  { id: '10A0865', location: 'E.1.5.B', name: 'COURROIE', stock: 6, packaging: 'PIEC', price: 11, status: 'Actif' },
  { id: '10A0875', location: 'E.1.4.F', name: 'COURROIE', stock: 12, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '10A0920', location: 'E.1.4.C', name: 'COURROIE', stock: 5, packaging: 'PIEC', price: 14, status: 'Actif' },
  { id: '10A0935', location: 'E.1.2.E', name: 'COURROIE', stock: 4, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '10A0940', location: 'E.1.2.B', name: 'COURROIE', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '10A0960', location: 'E.1.3.B', name: 'COURROIE', stock: 6, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '10A1075', location: 'E.1.1.E', name: 'COURROIE', stock: 12, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '10A1113B', location: 'E.1.2.C', name: 'COURROIE', stock: 5, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '10A1200B', location: 'E.1.3.A', name: 'COURROIE', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '10A1275', location: 'E.1.3.E', name: 'COURROIE', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '1310636080', location: 'G.3.1.A', name: 'RICAMBI FILTER', stock: 4, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '1428.54', location: 'D.2.1.A', name: 'RACCORD AIR', stock: 3, packaging: 'PIEC', price: 30, status: 'Actif' },
  { id: '1457801', location: 'F.2.5.E', name: 'VOYANT AVANT CRISTAL', stock: 8, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '1517081', location: 'F.2.6.E', name: 'VOYANT ARRIERE', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '1708', location: 'F.2.5.C', name: 'PLAQUES A BORNE8', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '20169', location: 'A.1.2.C', name: 'PEINTURE DE PRODEC', stock: 4, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '205', location: 'A.1.2.B', name: 'VERNIS PRE CATALYSE', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '25021801', location: 'F.3.6.D', name: 'VOYANT ARRIERE', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '251163', location: 'D.1.6.D', name: 'COMMUTATEUR', stock: 3, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '251275', location: 'F.2.3.E', name: 'VALEO COMMUTATEUR', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '25153801', location: 'F.2.6.D', name: 'PL.EQU.X53', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '2581828', location: 'F.3.2.A', name: 'SERRAGE', stock: 5, packaging: 'SAC', price: 10, status: 'Actif' },
  { id: '2590144', location: 'A.2.1.J', name: 'JEU DE CONTACT', stock: 3, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '2785Y- 916R', location: 'F.1.2.G', name: 'NGK SPARK PLUG CO. LTD', stock: 3, packaging: 'PIEC', price: 30, status: 'Actif' },
  { id: '2HLDR', location: 'F.1.6.F', name: 'BOUGIE SPARK PLUG', stock: 2, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '30137801', location: 'F.2.5.F', name: 'VOYANT LATERAL BICOLORE', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '31205', location: 'A.2.4.N', name: 'POMPE', stock: 7, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '3172', location: 'F.1.1.C', name: 'BOUGIE UR6ET', stock: 12, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '328775', location: 'A.2.1.D', name: 'ENS PROTECTION', stock: 10, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '350234', location: 'A.2.2.K', name: 'MAITRE CYLINDRE', stock: 6, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '350243', location: 'A.2.2.H', name: 'MAITRE CYLINDRE', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '350287', location: 'A.2.3.F', name: 'CYLINDRE DE ROUE', stock: 12, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '350307', location: 'A.2.3.B', name: 'CYLINDRE DE ROUE', stock: 3, packaging: 'PIEC', price: 18, status: 'Actif' },
  { id: '350342', location: 'B.2.2.F', name: 'CYLINDRE DE ROUE', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '350516', location: 'A.2.2.L', name: 'MAITRE CYLINDRE', stock: 4, packaging: 'PIEC', price: 35, status: 'Actif' },
  { id: '350526', location: 'D.3.1.F', name: 'MAÎTRE CYLINDRE', stock: 1, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '350538', location: 'C.1.2.E', name: 'VALEO CYLINDRE DR ROUE', stock: 3, packaging: 'PIEC', price: 17.5, status: 'Actif' },
  { id: '350557', location: 'B.2.2.D', name: 'CYLINDRE DE ROUE', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '350582', location: 'A.2.2.E', name: 'MAÎTRE CYLINDRE', stock: 4, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '350586', location: 'A.2.2.C', name: 'CYLINDRE DE ROUE', stock: 5, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '350595', location: 'C.1.1.D', name: 'CYLINDRE A HUILLE', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '350634', location: 'C.1.4.G', name: 'CYLINDRE DE ROUE', stock: 1, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '350637', location: 'A.2.2.J', name: 'MAITRE CYLINDRE', stock: 4, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '350671', location: 'A.2.2.I', name: 'MAITRE CYLINDRE', stock: 6, packaging: 'PIEC', price: 19, status: 'Actif' },
  { id: '350724', location: 'A.2.2.G', name: 'MAITRE CYLINDRE', stock: 7, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '350741', location: 'B.2.1.A', name: 'CYLINDRE DE ROUE', stock: 5, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '350867', location: 'A.2.2.F', name: 'MAITRE CYLINDRE', stock: 4, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '350935', location: 'A.2.3.C', name: 'CYLINDRE DE ROUE', stock: 9, packaging: 'PIEC', price: 28, status: 'Actif' },
  { id: '350944', location: 'A.2.2.D', name: 'CYLINDRE DE ROUE', stock: 3, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: '350945', location: 'B.2.1.C', name: 'CCYLINDRE DE ROUE', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '350952', location: 'A.2.3.G', name: 'CYLINDRE DE ROUE', stock: 4, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '350955', location: 'D.3.1.E', name: 'CYLINDRE DE ROUE', stock: 3, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '350973', location: 'A.2.3.H', name: 'CYLINDRE DE ROUE', stock: 1, packaging: 'PIEC', price: 45, status: 'Actif' },
  { id: '350974', location: 'B.2.2.A', name: 'CYLINDRE DE ROUE', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '350975', location: 'B.2.2.G', name: 'CYLINDRE DE ROUE', stock: 4, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '350979', location: 'B.2.2.E', name: 'CYLINDRE DE ROUE', stock: 2, packaging: 'PIEC', price: 6, status: 'Actif' },
  { id: '350983', location: 'A.2.3.E', name: 'CYLINDRE DE ROUE', stock: 2, packaging: 'PIEC', price: 33, status: 'Actif' },
  { id: '350986', location: 'A.2.3.A', name: 'CYLINDRE DE ROUE', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '352-21991', location: 'F.3.1.E', name: 'BOUCHON OREILLE', stock: 4, packaging: 'PIEC', price: 18, status: 'Actif' },
  { id: '357579', location: 'D.1.6.G', name: 'BUTEE', stock: 9, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '383004', location: 'D.2.5.F', name: 'CYLINDRE', stock: 9, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '4017.01', location: 'D.2.4.A', name: 'MACHOIRE DE FREIN', stock: 7, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '4017.02', location: '', name: 'MACHOIRE DE FREIN', stock: 3, packaging: '', price: 16, status: 'Actif' },
  { id: '402003', location: 'A.2.3.D', name: 'CYLINDRE DE ROUE', stock: 9, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '402012', location: 'B.2.2.H', name: 'CYLINDRE DE ROUE', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '402079', location: '', name: 'MAITRE CYLINDRE', stock: 4, packaging: 'PIEC', price: 6, status: 'Actif' },
  { id: '402095', location: 'D.2.1.G', name: 'MAITRE CYLINDRE', stock: 4, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '402099', location: 'A.2.2.M', name: 'MAITRE CYLINDRE', stock: 3, packaging: 'PIEC', price: 13, status: 'Actif' },
  { id: '402262', location: 'B.2.5.C', name: 'CYLINDRE DE ROUE', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '4027.01', location: 'D.1.4.D', name: 'MACHOIRE DE FREIN', stock: 4, packaging: 'PIEC', price: 11, status: 'Actif' },
  { id: '40405033', location: 'A.2.2.B', name: 'TÊTE D ALLUMAGE', stock: 9, packaging: 'PIEC', price: 9, status: 'Actif' },
  { id: '411320650', location: 'F.3.4.A', name: 'RIVETS', stock: 9, packaging: 'B500', price: 7, status: 'Actif' },
  { id: '411400800', location: 'F.3.4.B', name: 'RIVETS', stock: 7, packaging: 'B500', price: 18, status: 'Actif' },
  { id: '411401000', location: 'F.3.4.D', name: 'RIVETS', stock: 3, packaging: 'B500', price: 9, status: 'Actif' },
  { id: '411481300', location: 'F.3.4.E', name: 'RIVETS', stock: 2, packaging: 'B500', price: 7, status: 'Actif' },
  { id: '4130.00', location: '', name: 'MACHOIRE DE FREIN', stock: 9, packaging: '', price: 5, status: 'Actif' },
  { id: '41303103', location: 'B.2.5.E', name: 'CAPSULE A DEPRESSION', stock: 4, packaging: 'PIEC', price: 14, status: 'Actif' },
  { id: '4169.02', location: 'D.1.4.B', name: 'MACHOIRE DE FREIN', stock: 4, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '42.109', location: 'F.3.5.C', name: 'ÉCLAIRAGE PLAQUE IMMATRICULATION', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '42.487', location: 'A.2.4.D', name: 'VOYANT ARRIERE', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '42076', location: 'F.2.6.A', name: 'CABOCHON', stock: 3, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '423502P', location: 'A.2.1.H', name: 'JOINT POMPE A EAU', stock: 4, packaging: 'PIEC', price: 19, status: 'Actif' },
  { id: '423630P', location: 'E.1.6.B', name: 'J T COUVRE CULASSE', stock: 9, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: '4310.67', location: 'D.2.2.E', name: 'COLLECTION DE MÉCANISME', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '433215', location: 'A.1.3.B', name: 'DEMARREUR STARTER MOTOR', stock: 9, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '433297', location: 'A.1.3.D', name: 'DEMARREUR STARTER MOTOR', stock: 7, packaging: 'BLI2', price: 15, status: 'Actif' },
  { id: '436031', location: 'A.1.3.A', name: 'DÉMARREUR STARTER MOTOR', stock: 1, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '455746', location: 'A.1.3.C', name: 'DEMARREUR STARTER MOTOR', stock: 5, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '46130601', location: 'F.2.6.B', name: 'CATADIOPTRE', stock: 2, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '463575', location: 'F.2.6.F', name: 'RÉSERVOIR', stock: 1, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '474656', location: 'A.1.4.D', name: 'POMPE A ESSENCE', stock: 8, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '4806.50', location: 'D.2.2.F', name: 'FLEXIBLE FREIN', stock: 5, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '4806.65', location: 'D.2.2.B', name: 'FLEXIBLE FREIN', stock: 11, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '4849406', location: 'B.2.3.G', name: 'BOUGIE', stock: 6, packaging: 'PIEC', price: 8, status: 'Actif' },
  { id: '4950Y-924U', location: 'B.2.3.H', name: 'BOUGIE', stock: 7, packaging: 'PIEC', price: 5, status: 'Actif' },
  { id: '49590306', location: 'D.1.1.A', name: 'PRISE DE REMORQUE', stock: 7, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '5001.00', location: 'D.1.5.A', name: 'KIT', stock: 6, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '5002.00', location: 'A.2.4.L', name: 'KIT ET ANCHOITE', stock: 3, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: '5004.00', location: 'D.1.5.D', name: 'KIT', stock: 3, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '502134', location: 'F.2.4.E', name: 'VOYANT VERT', stock: 3, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '5021340', location: 'A.2.4.M', name: 'TUYAUX', stock: 6, packaging: 'PIEC', price: 5, status: 'Actif' },
  { id: '5108', location: 'C.1.4.C', name: 'VEILLAT', stock: 9, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '51324', location: 'F.2.1.A', name: 'RETROVISEUR BSCT (MANUEL)', stock: 7, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '525378', location: 'A.2.2.O', name: 'ALLUMAGE', stock: 1, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540029', location: 'E.3.5.B', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540030', location: 'E.3.4.A', name: 'PLAQUETTE DE FREIN', stock: 7, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '540042', location: 'E.3.6.C', name: 'PLAQUETTE DE FREIN', stock: 8, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '540075', location: 'E.3.6.B', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '540111', location: 'E.1.6.D', name: 'PLAQUETTE DE FREIN', stock: 10, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540125', location: 'E.3.1.A', name: 'PLAQUETTE DE FREIN', stock: 7, packaging: 'PIEC', price: 18, status: 'Actif' },
  { id: '540141', location: 'E.3.2.C', name: 'PLAQUETTES DE FREINS', stock: 6, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '540162', location: 'E.3.5.D', name: 'PLAQUETTE DE FREIN', stock: 2, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '540408', location: 'E.3.3.F', name: 'PLAQUETTES DE FREINS', stock: 1, packaging: 'PIEC', price: 16, status: 'Actif' },
  { id: '540410', location: 'A.2.3.O', name: 'PLAQUETTE DE FREIN', stock: 1, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '540414', location: 'D.1.6.C', name: 'PLAQUETTE DE FREIN', stock: 5, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '540418', location: 'A.2.3.R', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540422', location: 'A.2.3.P', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: '540426', location: 'A.2.3.K', name: 'PLAQUETTES DE FREIN', stock: 1, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '540433', location: 'E.3.6.D', name: 'PLAQUETTE DE FREIN', stock: 8, packaging: 'PIEC', price: 13, status: 'Actif' },
  { id: '540435', location: '', name: 'PLAQUETTES DE FREIN', stock: 11, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540439', location: 'E.3.5.C', name: 'PLAQUETTE DE FREIN', stock: 8, packaging: 'PIEC', price: 13, status: 'Actif' },
  { id: '540460', location: 'E.3.4.B', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 9, status: 'Actif' },
  { id: '540495', location: 'E.3.3.C', name: 'PLAQUETTES DE FREINS', stock: 2, packaging: 'PIEC', price: 7, status: 'Actif' },
  { id: '540497', location: 'E.3.2.D', name: 'PLAQUETTES DE FREINS', stock: 6, packaging: 'PIEC', price: 11, status: 'Actif' },
  { id: '540499', location: 'E.2.6.E', name: 'PLAQUETTE DE FREIN', stock: 12, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540502', location: 'E.2.5.E', name: 'PLAQUETTE DE FREIN', stock: 5, packaging: 'PIEC', price: 14, status: 'Actif' },
  { id: '540535', location: 'E.2.5.D', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540547', location: 'E.2.1.B', name: 'PLAQUETTE DE FREIN', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540748B', location: 'E.2.2.E', name: 'PLAQUETTE DE FREIN', stock: 6, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540781', location: 'E.2.2.C', name: 'PLAQUETTE DE FREIN', stock: 12, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '540795', location: 'E.2.2.D', name: 'PLAQUETTE DE FREIN', stock: 5, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540796', location: 'E.3.2.B', name: 'PLAQUETTES DE FREINS', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540854', location: 'E.3.2.G', name: 'PLAQUETTES DE FREINS', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '540943', location: 'E.3.1.B', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '540972', location: 'D.2.6.F', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 30, status: 'Actif' },
  { id: '545421', location: 'D.2.1.F', name: 'POSE BATTERIE', stock: 8, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '5468XS', location: 'A.1.4.F', name: 'COUROI', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551006', location: 'E.2.3.E', name: 'PLAQUETTE DE FREIN', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551016', location: 'E.3.5.E', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551029', location: 'B.2.2.C', name: 'PLAQUETTES DE FREINS', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551033', location: 'E.3.3.E', name: 'PLAQUETTES DE FREINS', stock: 6, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551035', location: 'E.2.5.C', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551036', location: 'E.2.5.B', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '551040', location: 'E.3.5.A', name: 'PLAQUETTE DE FREIN', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551427', location: 'E.3.3.G', name: 'PLAQUETTES DE FREINS', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551447', location: 'E.1.5.E', name: 'PLAQUETTE DE FREIN', stock: 5, packaging: 'SAC', price: 10, status: 'Actif' },
  { id: '551450', location: 'E.3.3.D', name: 'PLAQUETTES DE FREINS', stock: 3, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '551451', location: 'E.2.1.C', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 30, status: 'Actif' },
  { id: '551474', location: 'E.3.2.A', name: 'PLAQUETTES DE FREINS', stock: 2, packaging: 'PIEC', price: 20, status: 'Actif' },
  { id: '551522', location: 'E.3.6.E', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551732', location: 'E.2.2.B', name: 'PLAQUETTE DE FREIN', stock: 7, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '551795', location: 'E.2.1.A', name: 'PLAQUETTE DE FREIN', stock: 12, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '578083', location: 'A.2.1.K', name: 'CAPUCHON PORTE BALAI', stock: 10, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '578084', location: 'B.2.5.D', name: 'CAPUCHON POUR PORTE BALAI', stock: 6, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '582200T', location: 'D.1.6.B', name: 'TETE D\'ALLUMEUR', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '598006', location: 'E.3.1.C', name: 'PLAQUETTE DE FREIN', stock: 12, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '598009', location: 'E.3.4.D', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 18, status: 'Actif' },
  { id: '598019', location: 'E.3.2.E', name: 'PLAQUETTES DE FREINS', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '598040', location: 'E.2.1.E', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 35, status: 'Actif' },
  { id: '598080', location: 'E.2.4.B', name: 'PLAQUETTE DE FREIN', stock: 1, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '598081', location: 'E.2.4.D', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 17.5, status: 'Actif' },
  { id: '598086', location: 'E.2.3.B', name: 'PLAQUETTE DE FREIN', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '598098', location: 'E.2.3.A', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '598116', location: 'E.2.5.A', name: 'PLAQUETTE DE FREIN', stock: 5, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '598120', location: 'E.2.6.B', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '598126', location: 'E.2.4.A', name: 'PLAQUETTE DE FREIN', stock: 1, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '598131', location: 'C.1.2.B', name: 'VALEO PLAQUETTES DE FREIN', stock: 4, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '598143', location: 'E.2.6.A', name: 'PLAQUETTE DE FREIN', stock: 6, packaging: 'PIEC', price: 19, status: 'Actif' },
  { id: '598199', location: 'A.2.3.I', name: 'PLAQUETTE DE FREIN', stock: 7, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '598208', location: 'E.2.4.C', name: 'PLAQUETTE DE FREIN', stock: 5, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '598243', location: 'E.3.1.G', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '598268', location: 'E.2.6.D', name: 'PLAQUETTE DE FREIN', stock: 9, packaging: 'PIEC', price: 28, status: 'Actif' },
  { id: '598286', location: 'E.2.4.E', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: '598300', location: 'E.2.1.D', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '598309', location: 'A.2.3.J', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '598321', location: 'E.3.3.A', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '598379', location: 'B.2.2.B', name: 'PLAQUETTE DE FREIN', stock: 1, packaging: 'PIEC', price: 45, status: 'Actif' },
  { id: '598390', location: 'A.2.3.M', name: 'PLAQUETTES DE FREIN', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '598391', location: 'E.2.2.A', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '598429', location: 'E.3.4.C', name: 'PLAQUETTE DE FREIN', stock: 2, packaging: 'PIEC', price: 6, status: 'Actif' },
  { id: '598437', location: 'B.2.1.B', name: 'PLAQUETTE DE FREIN', stock: 2, packaging: 'PIEC', price: 33, status: 'Actif' },
  { id: '598464', location: 'E.3.4.E', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '598492', location: 'E.2.3.C', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 18, status: 'Actif' },
  { id: '598521', location: 'A.2.3.Q', name: 'PLAQUETTE DE FREIN', stock: 9, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '598543', location: 'E.3.1.E', name: 'PLAQUETTE DE FREIN', stock: 9, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '598578', location: 'E.3.1.D', name: 'PLAQUETTE DE FREIN', stock: 7, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '599544', location: 'E.2.6.C', name: 'PLAQUETTE DE FREIN', stock: 3, packaging: '', price: 16, status: 'Actif' },
  { id: '5998293-1', location: 'D.2.1.D', name: 'FILTRE A AIR', stock: 2, packaging: '', price: 55, status: 'Actif' },
  { id: '6000.EE', location: 'D.2.3.D', name: 'ROULEMENT', stock: 9, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '602470', location: 'A.2.2.A', name: 'DEMI-RONDE', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '602895', location: 'E.3.2.G', name: 'PLAQUETTES DE FREINS', stock: 4, packaging: 'PIEC', price: 6, status: 'Actif' },
  { id: '60983', location: 'E.3.6.A', name: 'PLAQUETTE DE FREIN', stock: 4, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '61570014', location: 'D.1.1.B', name: 'COMMUTATEUR', stock: 3, packaging: 'PIEC', price: 13, status: 'Actif' },
  { id: '62.131', location: 'F.3.6.E', name: 'VOYANT ARRIERE', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '62.260', location: 'F.3.6.C', name: 'BLOQUE OPTICO', stock: 4, packaging: 'PIEC', price: 11, status: 'Actif' },
  { id: '6201.EE', location: 'D.2.3.C', name: 'ROULEMENT', stock: 9, packaging: 'PIEC', price: 9, status: 'Actif' },
  { id: '6269M.C', location: 'E.1.2.D', name: 'CORROIE', stock: 9, packaging: 'B500', price: 7, status: 'Actif' },
  { id: '6295673', location: 'F.3.4.C', name: 'RIVETS YALU.4.8X20MS', stock: 7, packaging: 'B500', price: 18, status: 'Actif' },
  { id: '6300499', location: 'F.3.4.F', name: 'RIVETS', stock: 3, packaging: 'B500', price: 9, status: 'Actif' },
  { id: '6308-2Z', location: 'D.3.4.E', name: 'KIT DE ROULEMENT DE ROUE', stock: 2, packaging: 'B500', price: 7, status: 'Actif' },
  { id: '6309-2Z', location: 'D.3.4.D', name: 'KIT DE ROULEMENT DE ROUE', stock: 9, packaging: '', price: 5, status: 'Actif' },
  { id: '643817', location: 'D.2.6.D', name: 'TEMPORISATEUR', stock: 9, packaging: '', price: 10, status: 'Actif' },
  { id: '64H3E', location: 'F.1.6.E', name: 'BOUGIE VALEO', stock: 4, packaging: 'PIEC', price: 14, status: 'Actif' },
  { id: '660/21233/17', location: 'F.3.6.A', name: 'PLAQUETTE FREIN', stock: 4, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '67HP', location: 'F.1.6.D', name: 'BOUGIE VALEO', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '6PK1053', location: 'E.1.5.D', name: 'COURROIE', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '6PK1736', location: 'E.1.1.C', name: 'COURROIE', stock: 3, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '6PK975', location: 'E.1.2.A', name: 'COURROIE', stock: 4, packaging: 'PIEC', price: 19, status: 'Actif' },
  { id: '7008', location: 'C.1.2.C', name: 'AMPOULE PHILIPS', stock: 9, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: '70086V', location: 'D.2.1.B', name: 'AMPOULE', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '71045360', location: 'F.2.3.B', name: 'SEIMA', stock: 4, packaging: 'PIEC', price: 25, status: 'Actif' },
  { id: '7130', location: 'F.2.5.B', name: 'AMPOULES', stock: 2, packaging: 'PIEC', price: 6, status: 'Actif' },
  { id: '7320/2', location: 'D.2.2.C', name: 'KIT POMPE A VIDE', stock: 2, packaging: 'PIEC', price: 33, status: 'Actif' },
  { id: '7533BA15S', location: 'F.1.3.E', name: 'AMPOULE OSRAM', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '7700763315', location: 'D.2.2.A', name: 'PIÈCE D\'ORIGINE', stock: 4, packaging: 'PIEC', price: 18, status: 'Actif' },
  { id: '7700859220', location: 'E.1.1.A', name: 'JOINT', stock: 9, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '7701042499', location: 'G.2.1.D', name: 'RENAULT FILTER', stock: 9, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: '7701349425', location: 'E.1.3.D', name: 'COURROIE', stock: 7, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '770146816', location: 'A.1.4.G', name: 'COURROIE', stock: 3, packaging: '', price: 16, status: 'Actif' },
  { id: '7701469665', location: 'A.2.1.L', name: 'ROTULE DE DIRECTION', stock: 2, packaging: '', price: 55, status: 'Actif' },
  { id: '7711497267', location: 'D.2.4.B', name: 'MOTEUR', stock: 9, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: '811775', location: 'C.1.2.H', name: 'BOUCHON VIDANGE', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '813355', location: 'B.2.3.I', name: 'SIMULATEUR D\'ALARME', stock: 4, packaging: 'PIEC', price: 6, status: 'Actif' },
  { id: '8478', location: 'D.3.2.A', name: 'POMPE A ESSENCE', stock: 4, packaging: 'PIEC', price: 15, status: 'Actif' },
  { id: '848CJ8Y', location: 'B.2.3.F', name: 'BOUGIE', stock: 3, packaging: 'PIEC', price: 13, status: 'Actif' },
  { id: '8H', location: 'F.1.6.H', name: 'BOUGIE VALEO', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: '9328', location: 'F.2.6.C', name: 'FEU DE CLIGNOTANT', stock: 4, packaging: 'PIEC', price: 11, status: 'Actif' },
  { id: '942047', location: 'F.2.1.D', name: 'ADAPTATEUR DE CONNEXION', stock: 9, packaging: 'PIEC', price: 9, status: 'Actif' },
  { id: '97134032', location: 'F.1.2.B', name: 'BOUGIE MARCHAL', stock: 9, packaging: 'B500', price: 7, status: 'Actif' },
  { id: '98190107', location: 'F.3.1.D', name: 'FEU AVANT BICOLORE', stock: 7, packaging: 'B500', price: 18, status: 'Actif' },
  { id: '98190219', location: 'F.3.5.B', name: 'AEBRAN AVANT FUME', stock: 3, packaging: 'B500', price: 9, status: 'Actif' },
  { id: 'A194', location: 'G.2.5.D', name: 'FILTRES PURFLUX', stock: 2, packaging: 'B500', price: 7, status: 'Actif' },
  { id: 'A266', location: 'G.2.1.B', name: 'FILTRES PURFLUX', stock: 9, packaging: '', price: 5, status: 'Actif' },
  { id: 'A355', location: 'G.2.7.A', name: 'FILTRES PURFLUX', stock: 9, packaging: '', price: 10, status: 'Actif' },
  { id: 'A363', location: 'C.2.3.C', name: 'FILTRE A AIR', stock: 4, packaging: 'PIEC', price: 14, status: 'Actif' },
  { id: 'A416', location: 'G.2.1.C', name: 'FILTRES PURFLUX', stock: 4, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: 'A422', location: 'G.2.3.A', name: 'FILTRES PURFLUX', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: 'A460', location: 'G.2.2.A', name: 'FILTRES PURFLUX', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: 'A462', location: 'G.2.6.B', name: 'FILTRES PURFLUX', stock: 3, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: 'A503', location: 'G.2.7.B', name: 'FILTRES PURFLUX', stock: 4, packaging: 'PIEC', price: 19, status: 'Actif' },
  { id: 'A507', location: 'G.2.5.F', name: 'FILTRES PURFLUX', stock: 9, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: 'A518', location: 'G.2.6.D', name: 'FILTRES PURFLUX', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: 'A590', location: 'G.2.6.A', name: 'FILTRES PURFLUX', stock: 7, packaging: 'B500', price: 18, status: 'Actif' },
  { id: 'A753', location: 'G.2.5.C', name: 'FILTRES PURFLUX', stock: 3, packaging: 'B500', price: 9, status: 'Actif' },
  { id: 'A817', location: 'G.2.2.B', name: 'FILTRES PURFLUX', stock: 2, packaging: 'B500', price: 7, status: 'Actif' },
  { id: 'A935', location: 'G.2.1.A', name: 'FILTRES PURFLUX', stock: 9, packaging: '', price: 5, status: 'Actif' },
  { id: 'ADK043', location: 'A.2.4.I', name: 'KIT FREIN TAMBOUR', stock: 9, packaging: '', price: 10, status: 'Actif' },
  { id: 'ART-290', location: 'B.2.2.I', name: 'COSSE BATTERIE', stock: 4, packaging: 'PIEC', price: 14, status: 'Actif' },
  { id: 'B518', location: 'D.2.6.E', name: 'TETE D\'ALLUMEUR', stock: 4, packaging: 'PIEC', price: 12, status: 'Actif' },
  { id: 'B60', location: 'D.2.3.G', name: 'BOUCHON ANTI-VOL', stock: 3, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: 'BCP 6 ES', location: 'F.1.1.F', name: 'NGK BOUGIE D\'ALLUMAGE', stock: 2, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: 'BF700X', location: 'H.2.3.D', name: 'FILTRE CARBURANT', stock: 3, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: 'BKR5EK', location: 'C.1.3.F', name: 'BOUGIE', stock: 4, packaging: 'PIEC', price: 19, status: 'Actif' },
  { id: 'BKR6E', location: 'B.2.3.D', name: 'BOUGIE', stock: 9, packaging: 'PIEC', price: 17, status: 'Actif' },
  { id: 'BKR6EZ', location: 'C.1.3.I', name: 'BOUGIE', stock: 9, packaging: 'PIEC', price: 10, status: 'Actif' },
  { id: 'BL207', location: 'D.2.2.D', name: 'BOUCHON RADIATEUR', stock: 3, packaging: 'PIEC', price: 22, status: 'Actif' },
  { id: 'BL258', location: 'D.2.3.A', name: 'BOUCHON RADIATEUR', stock: 4, packaging: 'PIEC', price: 19, status: 'Actif' },
  { id: 'BP5ET', location: 'F.1.6.B', name: 'BOUGIE NGK', stock: 9, packaging: 'PIEC', price: 17, status: 'Actif' },
];
